# Generated by Django 3.1.8 on 2021-08-16 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210816_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedphone',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
