# Generated by Django 3.1.8 on 2021-08-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_observedphone_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedphone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
