# Generated by Django 3.1.8 on 2021-09-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_observedphone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(default='zł', max_length=3),
        ),
    ]
