# Generated by Django 3.1.8 on 2021-09-19 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210905_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='PLN', max_length=3)),
                ('display_name', models.CharField(default='zł', max_length=15)),
                ('country', models.CharField(default='Polska', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GB', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='url',
            field=models.URLField(default='https://url.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.currency'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.color'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='storage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.storageunit'),
        ),
    ]
