# Generated by Django 3.1.7 on 2021-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_phone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='img',
            field=models.ImageField(blank=True, upload_to='phones'),
        ),
    ]
