# Generated by Django 3.1.7 on 2021-04-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_phone_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='observed',
            field=models.BooleanField(default=False),
        ),
    ]
