version: "3.9"

x-envs:
  environment: &django-env
    DEBUG: "True"
    SECRET_KEY: ${SECRET_KEY:?provide secret key for django project}
    ALLOWED_HOSTS: ${ALLOWED_HOSTS:-127.0.0.1,localhost}
    DATABASE_URL: postgresql://postgres:postgres@postgresql:5432/kuptelefonik
    CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672

services:
  kuptelefonik:
    build: .
    container_name: kuptelefonik
    depends_on:
      - postgresql
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      <<: *django-env
    ports:
      - ${KUPTELEFONIK_PORT:-8000}:8000
    volumes:
      - ./:/opt/kuptelefonik
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
  postgresql:
    image: postgres
    container_name: postgresql
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kuptelefonik
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  celery_worker:
    build: .
    container_name: celery_worker
    depends_on:
      - rabbitmq
      - kuptelefonik
    command: celery -A kuptelefonik worker -l debug
    volumes:
      - ./:/opt/kuptelefonik
    environment:
      <<: *django-env
  celery_beat:
    build: .
    container_name: celery_beat
    depends_on:
      - rabbitmq
      - kuptelefonik
    command: celery -A kuptelefonik beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      <<: *django-env
  flower:
    image: mher/flower
    container_name: flower
    depends_on:
      - rabbitmq
      - celery_worker
      - celery_beat
    command: celery flower
    environment:
      <<: *django-env
    ports:
      - ${FLOWER_PORT:-5555}:5555

volumes:
  postgresql_data:
