# Generated by Django 3.1.8 on 2021-09-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0009_observedphone_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersScrapingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.phone')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop')),
            ],
        ),
    ]
