# Generated by Django 3.1.8 on 2021-09-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210919_2026'),
        ('data_collecting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offersscrapingdata',
            unique_together={('phone', 'shop')},
        ),
    ]
